# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UU3dVJH3MPfI6dFvKdFyyiUmsSGQtzd4
"""

pip install nltk scikit-learn

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# FAQ Data
questions = [
    "what is your name",
    "how can i apply",
    "what courses do you offer",
    "where are you located",
    "what is ai",
    "what is python"
]

answers = [
    "I am an AI chatbot created for FAQs.",
    "You can apply through our official website.",
    "We offer AI, Web Development, and Data Science courses.",
    "We are an online learning platform.",
    "AI stands for Artificial Intelligence.",
    "Python is a programming language used for AI and development."
]

# Vectorization
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(questions)

def get_response(user_input):
    user_input = user_input.lower()
    user_vec = vectorizer.transform([user_input])
    similarity = cosine_similarity(user_vec, X)
    index = similarity.argmax()
    return answers[index]

# Text-based interaction (replace GUI)
print("Chatbot: Hello! Ask me anything about our FAQs. Type 'quit' to exit.")
while True:
    user_input = input("You: ")
    if user_input.lower() == 'quit':
        print("Chatbot: Goodbye!")
        break
    response = get_response(user_input)
    print("Chatbot: " + response)